--!strict

const object = require("./object")
const declare = require("./static/declare")
const namefield = require("./static/namefield")

const private = {}
const class: declare.typeobject = object:new({
	type = namefield.typeobject,

	get_something = function (self: declare.typeobject) : ()
		
	end
})

class:toggle_host(function(new: declare.typeobject)
	
end)

do
	type private_type = {

	}

	private.table = {}

	function private.do_something (...: unknown)
		
	end
end


return class