[package]
name = "ifmnb/forgotten-grave"
version = "0.0.1"
license = "MIT"
authors = ["Aftersky"]
description = "Source code of ForgottenGrave game"

repository = "https://github.com/IFMNB/fog-rbx"
registry = "https://github.com/UpliftGames/wally-index"
private = true
realm = "shared"

[dependencies]
Concur = "sleitnick/concur@0.1.2" # Task async control
Quaternion = "sleitnick/quaternion@0.2.3" # Quaternion geometry
Videlib = "centau/vide@0.4.1" # UI Library
Lori = "kyrorblx/lori@0.1.7" # Debug manager
Konsole = "kyrorblx/konsole@0.1.11" # Console manager
Cryptography = "daily3014/cryptography@1.5.0" # Security/Hash
Squash = "data-oriented-house/squash@5.0.0" # Buffer/Ser

[server-dependencies]
# Cmdr = "evaera/cmdr@1.12.0" # outdated

[dev-dependencies]