--!strict

return table.freeze {
    core = "core" :: "core",
    struct = "struct" :: "struct",
    class = "class" :: "class",
    enum = "enum" :: "enum",
    
    game = "game" :: "game",
    geometry = "geometry" :: "geometry",
    common = "common" :: "common",

    immersiveness = "immersiveness" :: "immersiveness",
    inverse_kinematic = "inverse_kinematics" :: "immersiveness",
    solver = "solver" :: "solver"

}