--!strict

return table.freeze({
	["nil"] = "nil" :: "nil",
	["number"] = "number" :: "number",
	["string"] = "string" :: "string",
	["boolean"] = "boolean" :: "boolean",
	["table"] = "table" :: "table",
	["vector"] = "vector" :: "vector",
	["function"] = "function" :: "function",
	["thread"] = "thread" :: "thread",
	["userdata"] = "userdata" :: "userdata",
	["buffer"] = "buffer" :: "buffer",
	["anyt"] = "anyt" :: "anyt",

	is_primetive = function(t: unknown)
		const T = type(t)

		if t == "number" or t == "string" or t == "boolean" or t == "anyt" then
			return true
		end

		if T == "number" or T == "string" or T == "boolean" or T == "anyt" then
			return true
		end

		return false
	end,

	["roblox"] = table.freeze({
		["AdReward"] = "AdReward" :: "AdReward",
		["Axes"] = "Axes" :: "Axes",
		["BrickColor"] = "BrickColor" :: "BrickColor",
		["CatalogSearchParams"] = "CatalogSearchParams" :: "CatalogSearchParams",
		["CFrame"] = "CFrame" :: "CFrame",
		["Color3"] = "Color3" :: "Color3",
		["ColorSequence"] = "ColorSequence" :: "ColorSequence",
		["ColorSequenceKeypoint"] = "ColorSequenceKeypoint" :: "ColorSequenceKeypoint",
		["Content"] = "Content" :: "Content",
		["DateTime"] = "DateTime" :: "DateTime",
		["DockWidgetPluginGuiInfo"] = "DockWidgetPluginGuiInfo" :: "DockWidgetPluginGuiInfo",
		["Enum"] = "Enum" :: "Enum",
		["EnumItem"] = "EnumItem" :: "EnumItem",
		["Enums"] = "Enums" :: "Enums",
		["Faces"] = "Faces" :: "Faces",
		["FloatCurve"] = "FloatCurve" :: "FloatCurve",
		["Font"] = "Font" :: "Font",
		["Instance"] = "Instance" :: "Instance",
		["NumberRange"] = "NumberRange" :: "NumberRange",
		["NumberSequence"] = "NumberSequence" :: "NumberSequence",
		["NumberSequenceKeypoint"] = "NumberSequenceKeypoint" :: "NumberSequenceKeypoint",
		["OverlapParams"] = "OverlapParams" :: "OverlapParams",
		["Path2DControlPoint"] = "Path2DControlPoint" :: "Path2DControlPoint",
		["PathWaypoint"] = "PathWaypoint" :: "PathWaypoint",
		["PhysicalProperties"] = "PhysicalProperties" :: "PhysicalProperties",
		["Random"] = "Random" :: "Random",
		["Ray"] = "Ray" :: "Ray",
		["RaycastParams"] = "RaycastParams" :: "RaycastParams",
		["RaycastResult"] = "RaycastResult" :: "RaycastResult",
		["RBXScriptConnection"] = "RBXScriptConnection" :: "RBXScriptConnection",
		["RBXScriptSignal"] = "RBXScriptSignal" :: "RBXScriptSignal",
		["Rect"] = "Rect" :: "Rect",
		["Region3"] = "Region3" :: "Region3",
		["Region3int16"] = "Region3int16" :: "Region3int16",
		["RotationCurveKey"] = "RotationCurveKey" :: "RotationCurveKey",
		["Secret"] = "Secret" :: "Secret",
		["SecurityCapabilities"] = "SecurityCapabilities" :: "SecurityCapabilities",
		["SharedTable"] = "SharedTable" :: "SharedTable",
		["TweenInfo"] = "TweenInfo" :: "TweenInfo",
		["UDim"] = "UDim" :: "UDim",
		["UDim2"] = "UDim2" :: "UDim2",
		["UserValue"] = "UserValue" :: "UserValue",
		["Vector2"] = "Vector2" :: "Vector2",
		["Vector2int16"] = "Vector2int16" :: "Vector2int16",
		["Vector3"] = "Vector3" :: "Vector3",
		["Vector3int16"] = "Vector3int16" :: "Vector3int16",
	}),
})
