--!strict
const Maybe = require("@game/ReplicatedStorage/class/common/gc/Maybe")
const IKR6Foot = require("@game/ReplicatedStorage/class/game/play/characters/ik/r6/IKR6Foot")
const IKR6Solver = require("@game/ReplicatedStorage/class/game/play/characters/ik/r6/IKR6Solver")
const IKR6Info = require("@game/ReplicatedStorage/class/struct/game/IKR6Info")
const Basis = require("@game/ReplicatedStorage/class/struct/geometry/Basis")
const ConnectionVariant = require("@game/ReplicatedStorage/enums/descriptor/ConnectionVariant")
const ReferenceNotification = require("@game/ReplicatedStorage/enums/notification/ReferenceNotification")
const IKLegsState = require("@game/ReplicatedStorage/enums/state/IKLegsState")
const engine = require("@game/ReplicatedStorage/platform/engine")
const instance = require("@game/ReplicatedStorage/platform/instance")
const worldspace = require("@game/ReplicatedStorage/platform/worldspace")
const ctags = require("@game/ReplicatedStorage/static/ctags")
const ctype = require("@game/ReplicatedStorage/static/ctype")
const declare = require("@game/ReplicatedStorage/static/declare")
const ftype = require("@game/ReplicatedStorage/static/ftype")
const project = require("@game/ReplicatedStorage/static/project")

const private = {}
const class : ikr6legs = IKR6Solver:new {
    type = "ikr6legs",
    enabled = false,
    current_idle_time = 0,
    last_work_time = 0,

    get_left_leg = ftype:write(function (self: ikr6legs) : ikr6foot
        return private.maybe_left_legs:enactment(self, IKR6Foot)
    end, IKR6Foot.type, "ikr6legs"),

    get_right_leg = ftype:write(function (self: ikr6legs) : ikr6foot
        return private.maybe_right_legs:enactment(self, IKR6Foot)
    end, IKR6Foot.type, "ikr6legs"),

    get_active_cycle_leg_pair = ftype:write(function (self: ikr6legs) : (ikr6foot, ikr6foot)
        const left_leg = self:get_left_leg()
        if left_leg.current then 
            return left_leg, self:get_right_leg()
        end

        const right_leg = self:get_right_leg()

        if right_leg.current then
            return right_leg, self:get_left_leg()
        end

        return left_leg, right_leg
    end, ftype:var(IKR6Foot.type), "ikr6legs"),

    is_initiated = ftype:write(function (self: ikr6legs) : boolean
        return private.maybe_left_legs:exist(self) and private.maybe_right_legs:exist(self)
    end, declare.boolean, "ikr6legs"),

    is_active = ftype:write(function (self: ikr6legs) : boolean
        return private.active[self] or false
    end, declare.boolean, "ikr6legs")
}

do
    type raw = {
        read torso: basis,
        read size: vector,
        read move_dir: vector,
        read linear_vel: vector,
        read horizont_linear_vel: vector,
        read walkspeed: number,
        read speed_factor: number,
        read is_moving: boolean
    }
	private.rayparams = RaycastParams.new()
	private.rayparams.FilterType = Enum.RaycastFilterType.Exclude
	private.rayparams.RespectCanCollide = true
	private.rayparams.BruteForceAllSlow = false
	private.rayparams.IgnoreWater = true
    private.rayparams.ExcludeInstances = {}

    private.default_ikr6info = IKR6Info:new()
    private.list = setmetatable({} :: {ikr6legs}, declare.tables.__mode_vs)
    private.active = setmetatable({} :: {[ikr6legs]: boolean?}, declare.tables.__mode_ks)
    private.maybe_left_legs = Maybe:new() :: maybe<ikr6foot, ikr6legs>
    private.maybe_right_legs = Maybe:new() :: maybe<ikr6foot, ikr6legs>
    private.signal = engine.postphysic

    private.register_new = function (new: ikr6legs)
            const humanoid_reference = new:get_humanoid()

            humanoid_reference:subscribe({ReferenceNotification.NewInstance, ReferenceNotification.ChangedInstance}, ConnectionVariant.Ever, function ()
                if not humanoid_reference:is_instance_exists() then return end
                const humanoid = humanoid_reference:get_instance() :: Humanoid

                if not new:get_info().prebuild_fake then return end

                const left_leg = new:get_left_leg()
                if not left_leg:is_initiated() then
                    const limb_part = instance.humanoid.get_limb_of(humanoid, Enum.Limb.LeftLeg)
                    left_leg:get_reference():set_instance(limb_part)
                end
        
                const right_leg = new:get_right_leg()
                if not right_leg:is_initiated() then
                    const limb_part = instance.humanoid.get_limb_of(humanoid, Enum.Limb.RightLeg)
                    right_leg:get_reference():set_instance(limb_part)
                end

                if project.debug.state then
                    if right_leg:is_initiated() or left_leg:is_initiated() then
                        project.console_out("the humanoid changes for the already initialized ikr6legs, the limbs will not change")
                    end

                    if project.debug.show_ikr6legs_solver_path then
                        project.console_out("new humanoid setup")
                    end
                end
            end
        )

        new:set_info(private.default_ikr6info)
        new:watch(private.free_legs)

        const left_leg =  new:get_left_leg()
        const right_leg = new:get_right_leg()

        const left_leg_state_machine = left_leg:get_states()
        const right_leg_state_machine = right_leg:get_states()

        left_leg_state_machine:set_state(true, IKLegsState.Planted)
        right_leg_state_machine:set_state(true, IKLegsState.Planted)

        left_leg.current = true

        private.signal:Once(function ()
            table.insert(private.list, new)
        end)
    end

    do -- global utility layer
        private.modify_params = function (with: Instance): ()
            private.rayparams.ExcludeInstances = {with}
        end

        private.mark_unactive = function (ikr6legs: ikr6legs)
            private.active[ikr6legs] = false
        end
        
        private.create_raw = function (torso: BasePart, humanoid: Humanoid) : raw
            const dir, lin, size = worldspace.to_vector(humanoid.MoveDirection, torso.AssemblyLinearVelocity, torso.Size)
            const hor_lin_vel = vector.create(lin.x, 0, lin.z)

            return table.freeze {
                torso = Basis:to_basis(torso.CFrame),
                move_dir = dir,
                linear_vel = lin,
                size = size,
                horizont_linear_vel = hor_lin_vel,
                walkspeed = humanoid.WalkSpeed,
                speed_factor = math.clamp(vector.magnitude(hor_lin_vel) / math.max(humanoid.WalkSpeed, 0.001), 0, 1),
                is_moving = vector.magnitude(dir) >= 0.01
            }
        end

        private.free_legs = function (related: disposable)
            const self = related:as <<ikr6legs>>(class.type)

            table.remove(private.list, table.find(private.list, self) or 0)

            if private.maybe_left_legs:exist(self) then
                self:get_left_leg():free()
            end

            if private.maybe_right_legs:exist(self) then
                self:get_right_leg():free()
            end
        end

    end







    do -- leg world checks layer
        private.get_step_raycast_data = function (raw: raw, info: ikr6leginfo, predicted: vector, state: enumitem_iklegs_state) : (vector, vector)
            const up = raw.torso.rotation.up
            const down = -up

            const move_length = vector.magnitude(raw.move_dir)

            local horizontal_direction: vector

            if move_length > 0.001 then
                horizontal_direction = raw.move_dir / move_length
            else
                horizontal_direction = raw.torso.rotation.front
            end

            const origin = predicted + up * info.leg_raycast_up       
            const forward = if state == IKLegsState.Stepping then info.leg_step_forward elseif state == IKLegsState.Planted then info.leg_stand_forward elseif state == IKLegsState.Settling then info.leg_idle_step_forward else 1     
            const direction = horizontal_direction * forward + down * (info.leg_raycast_up + info.leg_raycast_down)

            return origin, direction
        end

        private.is_step_blocked = function (raw: raw, foot: ikr6foot, info: ikr6leginfo, predicted: vector): boolean
            const move_length = vector.magnitude(raw.move_dir)
            if move_length <= 1e-5 then return false end

            const direction = raw.move_dir / move_length
            const up = raw.torso.rotation.up
            const obstacle_origin = predicted + up * info.leg_step_obstacle_height
            const obstacle = worldspace.raycast(obstacle_origin, direction * info.limb_block_distance, private.rayparams)
            if not obstacle then return false end

            const normal, position = worldspace.to_vector(obstacle.Normal, obstacle.Position)
            if math.abs(vector.dot(normal, up)) > 0.5 then return false end

            const top_origin = position + direction * (info.limb_size.z * 0.5 + 0.05) + up * (info.leg_step_max_height + 0.05)
            const top_result = worldspace.raycast(top_origin, -up * (info.leg_step_max_height + 0.15), private.rayparams)
            if not top_result then return true end

            const top_normal, top_position = worldspace.to_vector(top_result.Normal, top_result.Position)
            if vector.dot(top_normal, up) < 0.7 then return true end

            const height = vector.dot(top_position - predicted, up)
            return height > info.leg_step_max_height
        end
    end

    do -- leg utility layer
        private.foot_update = function (raw: raw, foot: ikr6foot, info: ikr6leginfo, raycast_result: RaycastResult)
            foot.hit_normal, foot.hit_position = worldspace.to_vector(raycast_result.Normal, raycast_result.Position)
            foot.up_direction = raw.torso.rotation.up
            foot.fallback_basis = Basis:to_basis(foot:get_reference():get_instance().CFrame)
        end

        private.update_foot_anchor = function(raw: raw,foot: ikr6foot, info: ikr6leginfo)
            const previous_lateral_position = foot.lateral_position
            foot.from = raw.torso.position
            foot.lateral_position = raw.torso.position + vector.create(0, -raw.size.y / 2, 0) + raw.torso.rotation.right * info.limb_diff
            
            const delta = foot.lateral_position - previous_lateral_position
            const up = raw.torso.rotation.up
            const planar_delta = delta - up * vector.dot(delta, up)
            
            foot.accumulated_distance += vector.magnitude(planar_delta)
        end

        private.should_step = function(raw: raw, foot: ikr6foot, info: ikr6leginfo): boolean
            const contact = foot:get_limb_contact()
            const up = raw.torso.rotation.up

            const error_scale = (foot.lateral_position - contact) - up * vector.dot((foot.lateral_position - contact), up)
            const error_distance = vector.magnitude(error_scale)

            return error_distance >= info.limb_distance_trigger_at or foot.accumulated_distance >= info.limb_distance_trigger_at
        end

        private.get_step_speed = function (raw: raw, info: ikr6leginfo): number
            return info.limb_movement_speed_min + (info.limb_movement_speed_max - info.limb_movement_speed_min) *
                math.clamp(
                    (vector.magnitude(raw.horizont_linear_vel) - info.limb_movement_velocity_min) / -- speed
                    math.max(info.limb_movement_velocity_max - info.limb_movement_velocity_min, 0.001), -- factor
                    0, 1
                )
        end

        private.get_settle_speed = function (raw: raw, info: ikr6leginfo) : number
            return info.limb_orientation_speed_min + (info.limb_orientation_speed_max - info.limb_orientation_speed_min) * raw.speed_factor
        end
    end

    do -- leg placement layer
        private.step = function (raw: raw, foot: ikr6foot, info: ikr6leginfo, override: enumitem_iklegs_state?): (basis?, boolean)
            const prediction_factor = raw.speed_factor ^ info.limb_prediction_curve
            const prediction_time = info.limb_prediction_time_min + (info.limb_prediction_time_max - info.limb_prediction_time_min) * prediction_factor
            const predicted_bottom = foot.lateral_position + raw.horizont_linear_vel * prediction_time

            if private.is_step_blocked(raw, foot, info, predicted_bottom) then
                return nil, true
            end

            const raycast_origin, raycast_direction = private.get_step_raycast_data(raw, info, predicted_bottom, override or IKLegsState.Stepping)
            const raycast_result = worldspace.raycast(raycast_origin, raycast_direction, private.rayparams)
            if not raycast_result then
                foot.fallback = true
                return nil, false
            else
                foot.fallback = false
            end

            private.foot_update(raw, foot, info, raycast_result)

            const face = foot:get_limb_facing(raw.move_dir,raw.torso.rotation.front)
            const knee = foot:get_limb_pole(face,raw.torso.rotation.front)

            return foot:get_limb_basis(raw.torso, knee, face), false
        end

        private.stand = function (raw: raw, foot: ikr6foot, info: ikr6leginfo, override: enumitem_iklegs_state?) : basis?
            const raycast_origin, raycast_direction = private.get_step_raycast_data(raw, info, foot.lateral_position, override or IKLegsState.Planted)
            const raycast_result = worldspace.raycast(raycast_origin, raycast_direction, private.rayparams)
            if not raycast_result then return nil end

            private.foot_update(raw, foot, info, raycast_result)

            const knee = foot:get_limb_pole(vector.zero, raw.torso.rotation.front)
            const foot_facing_direction = foot:get_limb_facing(vector.zero, raw.torso.rotation.front)
            const leg_placement = foot:get_limb_basis(raw.torso, knee, foot_facing_direction)

            return leg_placement
        end
    end


    do -- solver utility layer

        private.solver_begin_step = function (foot: ikr6foot, new_target: basis, info: ikr6leginfo)
            foot.fallback = false
            foot.target = new_target
            foot.hit_position = new_target.position - new_target.rotation.up * (info.limb_size.y * 0.5)

            const foot_state_machine = foot:get_states()
            foot_state_machine:set_state(false, IKLegsState.Planted, IKLegsState.Settling)
            foot_state_machine:set_state(true, IKLegsState.Stepping)
        end
                
        private.solver_begin_idle_step = function (raw: raw, ikr6: ikr6legs) : boolean
            const active, other = ikr6:get_active_cycle_leg_pair()
            const active_state_machine = active:get_states()

            if not active_state_machine:get_state(IKLegsState.Planted) then
                return false
            end

            const info = other:get_info()
            const target_basis = private.stand(raw, other, info, IKLegsState.Settling)
            if not target_basis then return false end

            private.solver_begin_step(other, target_basis, info)
            active.current = false
            other.current = true

            return true
        end

        private.solver_begin_leg_fallback = function (ikr6foot: ikr6foot) : ()
            ikr6foot.fallback = true

            const origin = ikr6foot:get_reference():get_instance()
            const fallback = origin.CFrame
            const fallback_basis = Basis:to_basis(fallback)

            const state_machine = ikr6foot:get_states()

            ikr6foot.fallback_basis = fallback_basis
            ikr6foot.target = fallback_basis
            ikr6foot.hit_position = ikr6foot:get_limb_contact()
            ikr6foot.hit_normal = fallback_basis.rotation.up

            ikr6foot:get_fake():get_instance().CFrame = fallback

            state_machine:set_state(false, IKLegsState.Settling, IKLegsState.Stepping)
            state_machine:set_state(true, IKLegsState.Planted)
        end

        private.solver_independent_foot = function (raw: raw, foot: ikr6foot): ()
            if foot.fallback then return end

            const state_machine = foot:get_states()
            if not state_machine:get_state(IKLegsState.Planted) then return end

            const info = foot:get_info()
            if not private.should_step(raw, foot, info) then return end

            const target, blocked = private.step(raw, foot, info)
            if blocked then return end

            if target then
                private.solver_begin_step(foot, target, info)
                return
            end

            private.solver_begin_leg_fallback(foot)
        end

        private.solver_leg_fallback = function (ikr6foot: ikr6foot, info: ikr6leginfo, delta: number) : ()
            const origin: BasePart = ikr6foot:get_reference():get_instance()
            const fallback = origin.CFrame
            const fallback_basis = Basis:to_basis(fallback)

            const state_machine = ikr6foot:get_states()
            const fake_leg = ikr6foot:get_fake():get_instance()

            state_machine:set_state(false, IKLegsState.Settling, IKLegsState.Stepping)
            state_machine:set_state(true, IKLegsState.Planted)

            ikr6foot.fallback_basis = fallback_basis
            ikr6foot.target = fallback_basis
            ikr6foot.hit_position = ikr6foot:get_limb_contact()

            fake_leg.CFrame = fake_leg.CFrame:Lerp(fallback, 1 - math.exp(-info.limb_fallback_speed * delta))
        end

        private.solver_recover_fallback = function (raw: raw,foot: ikr6foot): ()
            if not foot.fallback then return end

            const info = foot:get_info()
            if not private.should_step(raw, foot, info) then return end

            const target, blocked = private.step(raw, foot, info)
            if blocked then return end

            if target then
                private.solver_begin_step(foot, target, info)
            end
        end

        private.solver_foot_stepping = function (raw: raw, ikr6foot: ikr6foot, info: ikr6leginfo, fake_leg: BasePart, delta: number)
            const alpha = 1 - math.exp(-private.get_step_speed(raw, info) * delta)

            const current = Basis:to_basis(fake_leg.CFrame)
            const target = ikr6foot.target
            const next_basis = current:slerp(target, alpha)
            const offset = target.position - next_basis.position
            const horizontal = vector.create(offset.x, 0, offset.z)
            const distance = vector.magnitude(horizontal)
            const lift = math.min(distance, 1)
            const position = vector.create(next_basis.position.x, target.position.y + lift, next_basis.position.z)
            const new_basis = next_basis:clone({position = position})
            fake_leg.CFrame = Basis:to_cframe(new_basis)

            return
        end

        private.solver_foot_settling = function (raw: raw, ikr6foot: ikr6foot, info: ikr6leginfo, fake_leg: BasePart, delta: number)
            fake_leg.CFrame = fake_leg.CFrame:Lerp(Basis:to_cframe(ikr6foot.target), 1 - math.exp(-private.get_settle_speed(raw, info) * delta))
            return
        end

        private.solver_foot = function (raw: raw, ikr6legs: ikr6legs, delta: number)
            if project.debug.state and	project.debug.show_ikr6legs_solver_path then
                project.console_out "foots"
            end

            for _, ikr6foot in {ikr6legs:get_left_leg(), ikr6legs:get_right_leg()} do
                if not ikr6foot.enabled then continue end

                const info = ikr6foot:get_info()
                const state_machine = ikr6foot:get_states()
                const fake_leg = ikr6foot:get_fake():get_instance()

                private.update_foot_anchor(raw, ikr6foot, info)

                if state_machine:get_state(IKLegsState.Stepping) then
                    private.solver_foot_stepping(raw, ikr6foot, info, fake_leg, delta)
                    
                    if ikr6foot:is_moving_finished() then
                        state_machine:set_state(false, IKLegsState.Stepping)
                        state_machine:set_state(true, IKLegsState.Settling)
                    end

                    continue
                end

                if ikr6foot.fallback then
                    private.solver_leg_fallback(ikr6foot, info, delta)
                    continue
                end

                ikr6foot.target = ikr6foot:get_limb_target()

                if state_machine:get_state(IKLegsState.Settling) then
                    private.solver_foot_settling(raw, ikr6foot, info, fake_leg, delta)

                    if ikr6foot:is_orientation_finished() then
                        state_machine:set_state(false, IKLegsState.Settling, IKLegsState.Stepping)
                        state_machine:set_state(true, IKLegsState.Planted)

                        ikr6foot.accumulated_distance = 0
                    end

                    continue
                end

                fake_leg.CFrame = fake_leg.CFrame:Lerp(Basis:to_cframe(ikr6foot.target), 1 - math.exp(-info.limb_planted_speed * delta))
            end
        end
    end

    private.solver_to_idle = function (raw: raw, ikr6foot: ikr6foot)
        if project.debug.state and	project.debug.show_ikr6legs_solver_path then
            project.console_out "move to idle"
        end

        const state_machine = ikr6foot:get_states()
        const info = ikr6foot:get_info()

        if state_machine:get_state(IKLegsState.Planted) then
            const target = private.stand(raw, ikr6foot, info, IKLegsState.Planted)

            if target then
                ikr6foot.target = target
                ikr6foot.hit_position = ikr6foot:get_limb_contact()
            end
        end
    end

    private.world_solver  = function (delta: number)
        if project.debug.state and	project.debug.show_ikr6legs_solver_path then
            project.console_out ("world solver with ikr6legs list:", #private.list )
        end

        -- '__mode = "s"` gives the GC the right to reduce the size of the table,
        -- but this may cause optimization failures, so we cannot table.clear(private.active)
        for i, _ in private.active do
            private.active[i] = false
        end

        for _, ik in private.list do
            if not ik.enabled then
                private.mark_unactive(ik)

                if project.debug.state and	project.debug.show_ikr6legs_solver_path then
                    project.console_out "world solver unable"
                end

                continue
            end

            const info = ik:get_info()

            if info.ignore_hertz_limit then
                private.solver(ik, info, delta)
                continue
            end

            const hertz = math.max(info.update_hertz, 0.00001)
            const interval = 1 / hertz

            ik.last_work_time += delta
            if ik.last_work_time >= interval then
                const work_delta = ik.last_work_time
                ik.last_work_time -= interval

                private.solver(ik, info, work_delta)
            else
                if project.debug.state and	project.debug.show_ikr6legs_solver_path then
                    project.console_out "world solver skip"
                end
            end
        end
    end

    private.solver = function (ik: ikr6legs, info: ikr6info, delta: number)
        if project.debug.state and project.debug.show_ikr6legs_solver_path then
            project.console_out(`solver ({ik:iden()})`)
        end

        const reference_to_humanoid = ik:get_humanoid()
        const humanoid = reference_to_humanoid:get_instance()
        if humanoid == nil then 
            private.mark_unactive(ik)

            if project.debug.state then
                project.console_out ('this solver has no humanoid, skip')
            end

            return
        end

        const torso = ik:get_torso():get_instance()
        if torso == nil then
            private.mark_unactive(ik) 

            if project.debug.state then
                project.console_out ('this solver has no torso, skip')
            end

            return
        end

        private.active[ik] = true
        private.modify_params(torso.Parent or torso)
        const raw = private.create_raw(torso, humanoid)

        
        ik.current_idle_time = if raw.is_moving then 0 else ik.current_idle_time + delta


        private.solver_foot(raw, ik, delta)

        const left_leg = ik:get_left_leg()
        const right_leg = ik:get_right_leg()

        private.solver_recover_fallback(raw, left_leg)
        private.solver_recover_fallback(raw, right_leg)

        if not raw.is_moving and ik.current_idle_time >= info.idle_time then
            private.solver_to_idle(raw, left_leg)
            private.solver_to_idle(raw, right_leg)
        end

        const left_fallback = left_leg.fallback
        const right_fallback = right_leg.fallback

        if left_fallback and right_fallback then
            return
        end

        if left_fallback ~= right_fallback then
            const independent = if left_fallback then right_leg else left_leg
            const fallback = if left_fallback then left_leg else right_leg

            independent.current = true
            fallback.current = false

            private.solver_independent_foot(raw, independent)
            return
        end

        const active, other = ik:get_active_cycle_leg_pair()
        if not active:get_states():get_state(IKLegsState.Planted) then return end

        const other_info = other:get_info()
        if not private.should_step(raw, other, other_info) then return end

        const target, blocked = private.step(raw, other, other_info)

        if blocked then
            private.solver_begin_idle_step(raw, ik)
            return
        end

        if not target then
            private.solver_begin_leg_fallback(other)
            return
        end

        private.solver_begin_step(other, target, other_info)

        active.current = false
        other.current = true
    end

    private.signal:Connect(private.world_solver)

    ctype:read(class):write_tag(ctags.immersiveness, ctags.inverse_kinematic, ctags.solver, ctags.class, ctags.game)
    class:host(private.register_new)

    if project.game.smalltalk_like then
        private.register_new(class)
    end
end

return class