#!/usr/bin/env fish

set backend studio

if test "$CI" = "true"
    set backend open-cloud
end

mkdir -p CI/output

if test (count $argv) -gt 0
    set test_file $argv[1]
    set filename (basename $test_file .luau)
    set filename (string replace -r '\.spec$' '' $filename)

    jest-roblox-cli \
        --backend $backend \
        --outputFile "CI/output/CI_$filename.json" \
        --formatters github-actions \
        $test_file
else
    jest-roblox-cli \
        --backend $backend \
        --outputFile "CI/output/CI_all.json" \
        --formatters github-actions
end

exit $status