name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install tools
        run: rokit install

      - name: Build release
        run: rojo build production.project.json -o build.rbxl

      - name: Publish to Roblox
        env:
          ROBLOX_OPEN_CLOUD_API_KEY: ${{ secrets.ROBLOX_OPEN_CLOUD_API_KEY }}
          ROBLOX_UNIVERSE_ID: ${{ vars.ROBLOX_UNIVERSE_ID }}
          ROBLOX_PLACE_ID: ${{ vars.ROBLOX_CI_PLACE_ID }}
        run: |
          curl \
            --fail-with-body \
            --request POST \
            "https://apis.roblox.com/universes/v1/$ROBLOX_UNIVERSE_ID/places/$ROBLOX_PLACE_ID/versions?versionType=Published" \
            --header "x-api-key: $ROBLOX_OPEN_CLOUD_API_KEY" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @build.rbxl